### ISSUE TITLE
Nothing is shown after docsig . 

### ISSUE THREAD

**Issue by Gabriel-p** [jshwi/docsig#350]
Hi, I'm testing this package on my code with `docsig .` and I get nothing back. Literally nothing. I'm using Sphinx's docstring format on my code. Is there some way to debug this?

Environment:

- Python version: 3.10.14
- docsig version: 0.54.1

**Comment by jshwi** [comment]
Hi @Gabriel-p 
You'll get nothing if there is nothing wrong with you're code. No output and a 0 exit stats
You can try it it with additional flags to check for problems not checked by default
You can also you `--verbose` to see which files are being checked, or which files are being ignored due to gitignore or exclusion rules
