### ISSUE TITLE
List instead of regex

### ISSUE THREAD

**Issue by LisPrzemyslaw** [jshwi/docsig#393]
Right now for excluding the files it is required to use regex. For the other tools like flake8 the exclude contain a list of paths which should be excluded.
The regex is really difficult to read write and also it is hard to hold it inside the .toml file. The regex pattern contains also `\`, `\\`, `\/` which are not allowed in a config files, you have to makes workaround for it. Also the regex is not the best option for the paths.

The solution can be a list which holds a paths and also file names. Then it easy to read and it is definitely more user friendly.
Example: `excluded=["src/design/*", "docs/*", "src/my_file.py"]`

**Comment by jshwi** [comment]
Hi @LisPrzemyslaw 
I've added a new option, excludes as well as exclude
excludes, as in excludes one or more paths
I couldn't add it instead of as it could break for people
Both can be used alone, or with each other
At least all the above should work, but please let me know if you spot a bug!
This will be available now under 0.60.0
Thanks!
Stephen
